spring:
  application:
    name: greeting

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

greeting-service:
  greeting: "Test alt e "
  default-value: "Valor default alt"


