spring:
  application:
    name: greeting

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

greeting-service:
  greeting: "Perf"
  default-value: "Você esta no profile perf"


