spring:
  application:
    name: greeting

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

greeting-service:
  greeting: "Teste"
  default-value: "Valor default qa"


