server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:  application:    name: cambio
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cambio?useTimezone=true&serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    url: jdbc:postgresql://localhost:5432/cambio
    schemas: public
    user: postgres
    password: postgres