server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rodrigo-lucio/curso-microservices-spring-boot-cloud
          #username: xxx
          #password: xxx
          default-label: main
          search-paths:
            - 'greeting*'
