name: Continuous Integration with GitHub

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on: [push]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login into Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}} 
          
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'           
          
      - name: Build Eureka Naming Server Docker image
        working-directory: ./naming-sever
        run: mvn clean package -DskipTests

      - name: Build API Gateway Docker image
        working-directory: ./api-gateway
        run: mvn clean package -DskipTests

      - name: Build Cambio Service Docker image
        working-directory: ./cambio
        run: mvn clean package -DskipTests

      - name: Build Book Service Docker image
        working-directory: ./book
        run: mvn clean package -DskipTests
        
      - name: Docker Compose Build
        working-directory: .
        run: docker-compose build       

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{secrets.DOCKER_USERNAME}}/naming-sever:latest ${{secrets.DOCKER_USERNAME}}/naming-sever:${{github.run_id}}
          docker tag ${{secrets.DOCKER_USERNAME}}/api-gateway:latest ${{secrets.DOCKER_USERNAME}}/api-gateway:${{github.run_id}}
          docker tag ${{secrets.DOCKER_USERNAME}}/book:latest ${{secrets.DOCKER_USERNAME}}/book:${{github.run_id}}
          docker tag ${{secrets.DOCKER_USERNAME}}/cambio:latest ${{secrets.DOCKER_USERNAME}}/cambio:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/naming-sever:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/naming-sever:latest
          docker push ${{secrets.DOCKER_USERNAME}}/api-gateway:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/api-gateway:latest
          docker push ${{secrets.DOCKER_USERNAME}}/book:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/book:latest
          docker push ${{secrets.DOCKER_USERNAME}}/cambio:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/cambio:latest
